// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/database (interfaces: Context)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_context.go -package=mocks Keyline/internal/database Context
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// ApplicationUserMetadata mocks base method.
func (m *MockContext) ApplicationUserMetadata() repositories.ApplicationUserMetadataRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationUserMetadata")
	ret0, _ := ret[0].(repositories.ApplicationUserMetadataRepository)
	return ret0
}

// ApplicationUserMetadata indicates an expected call of ApplicationUserMetadata.
func (mr *MockContextMockRecorder) ApplicationUserMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationUserMetadata", reflect.TypeOf((*MockContext)(nil).ApplicationUserMetadata))
}

// Applications mocks base method.
func (m *MockContext) Applications() repositories.ApplicationRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Applications")
	ret0, _ := ret[0].(repositories.ApplicationRepository)
	return ret0
}

// Applications indicates an expected call of Applications.
func (mr *MockContextMockRecorder) Applications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Applications", reflect.TypeOf((*MockContext)(nil).Applications))
}

// AuditLogs mocks base method.
func (m *MockContext) AuditLogs() repositories.AuditLogRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuditLogs")
	ret0, _ := ret[0].(repositories.AuditLogRepository)
	return ret0
}

// AuditLogs indicates an expected call of AuditLogs.
func (mr *MockContextMockRecorder) AuditLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuditLogs", reflect.TypeOf((*MockContext)(nil).AuditLogs))
}

// Credentials mocks base method.
func (m *MockContext) Credentials() repositories.CredentialRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credentials")
	ret0, _ := ret[0].(repositories.CredentialRepository)
	return ret0
}

// Credentials indicates an expected call of Credentials.
func (mr *MockContextMockRecorder) Credentials() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credentials", reflect.TypeOf((*MockContext)(nil).Credentials))
}

// Files mocks base method.
func (m *MockContext) Files() repositories.FileRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files")
	ret0, _ := ret[0].(repositories.FileRepository)
	return ret0
}

// Files indicates an expected call of Files.
func (mr *MockContextMockRecorder) Files() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockContext)(nil).Files))
}

// GroupRoles mocks base method.
func (m *MockContext) GroupRoles() repositories.GroupRoleRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupRoles")
	ret0, _ := ret[0].(repositories.GroupRoleRepository)
	return ret0
}

// GroupRoles indicates an expected call of GroupRoles.
func (mr *MockContextMockRecorder) GroupRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupRoles", reflect.TypeOf((*MockContext)(nil).GroupRoles))
}

// Groups mocks base method.
func (m *MockContext) Groups() repositories.GroupRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(repositories.GroupRepository)
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockContextMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockContext)(nil).Groups))
}

// OutboxMessages mocks base method.
func (m *MockContext) OutboxMessages() repositories.OutboxMessageRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxMessages")
	ret0, _ := ret[0].(repositories.OutboxMessageRepository)
	return ret0
}

// OutboxMessages indicates an expected call of OutboxMessages.
func (mr *MockContextMockRecorder) OutboxMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxMessages", reflect.TypeOf((*MockContext)(nil).OutboxMessages))
}

// PasswordRules mocks base method.
func (m *MockContext) PasswordRules() repositories.PasswordRuleRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordRules")
	ret0, _ := ret[0].(repositories.PasswordRuleRepository)
	return ret0
}

// PasswordRules indicates an expected call of PasswordRules.
func (mr *MockContextMockRecorder) PasswordRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordRules", reflect.TypeOf((*MockContext)(nil).PasswordRules))
}

// Projects mocks base method.
func (m *MockContext) Projects() repositories.ProjectRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Projects")
	ret0, _ := ret[0].(repositories.ProjectRepository)
	return ret0
}

// Projects indicates an expected call of Projects.
func (mr *MockContextMockRecorder) Projects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Projects", reflect.TypeOf((*MockContext)(nil).Projects))
}

// ResourceServerScopes mocks base method.
func (m *MockContext) ResourceServerScopes() repositories.ResourceServerScopeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceServerScopes")
	ret0, _ := ret[0].(repositories.ResourceServerScopeRepository)
	return ret0
}

// ResourceServerScopes indicates an expected call of ResourceServerScopes.
func (mr *MockContextMockRecorder) ResourceServerScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceServerScopes", reflect.TypeOf((*MockContext)(nil).ResourceServerScopes))
}

// ResourceServers mocks base method.
func (m *MockContext) ResourceServers() repositories.ResourceServerRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceServers")
	ret0, _ := ret[0].(repositories.ResourceServerRepository)
	return ret0
}

// ResourceServers indicates an expected call of ResourceServers.
func (mr *MockContextMockRecorder) ResourceServers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceServers", reflect.TypeOf((*MockContext)(nil).ResourceServers))
}

// Roles mocks base method.
func (m *MockContext) Roles() repositories.RoleRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Roles")
	ret0, _ := ret[0].(repositories.RoleRepository)
	return ret0
}

// Roles indicates an expected call of Roles.
func (mr *MockContextMockRecorder) Roles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Roles", reflect.TypeOf((*MockContext)(nil).Roles))
}

// SaveChanges mocks base method.
func (m *MockContext) SaveChanges(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChanges", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChanges indicates an expected call of SaveChanges.
func (mr *MockContextMockRecorder) SaveChanges(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChanges", reflect.TypeOf((*MockContext)(nil).SaveChanges), ctx)
}

// Sessions mocks base method.
func (m *MockContext) Sessions() repositories.SessionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sessions")
	ret0, _ := ret[0].(repositories.SessionRepository)
	return ret0
}

// Sessions indicates an expected call of Sessions.
func (mr *MockContextMockRecorder) Sessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sessions", reflect.TypeOf((*MockContext)(nil).Sessions))
}

// Templates mocks base method.
func (m *MockContext) Templates() repositories.TemplateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Templates")
	ret0, _ := ret[0].(repositories.TemplateRepository)
	return ret0
}

// Templates indicates an expected call of Templates.
func (mr *MockContextMockRecorder) Templates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Templates", reflect.TypeOf((*MockContext)(nil).Templates))
}

// UserRoleAssignments mocks base method.
func (m *MockContext) UserRoleAssignments() repositories.UserRoleAssignmentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRoleAssignments")
	ret0, _ := ret[0].(repositories.UserRoleAssignmentRepository)
	return ret0
}

// UserRoleAssignments indicates an expected call of UserRoleAssignments.
func (mr *MockContextMockRecorder) UserRoleAssignments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRoleAssignments", reflect.TypeOf((*MockContext)(nil).UserRoleAssignments))
}

// Users mocks base method.
func (m *MockContext) Users() repositories.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(repositories.UserRepository)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockContextMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockContext)(nil).Users))
}

// VirtualServers mocks base method.
func (m *MockContext) VirtualServers() repositories.VirtualServerRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VirtualServers")
	ret0, _ := ret[0].(repositories.VirtualServerRepository)
	return ret0
}

// VirtualServers indicates an expected call of VirtualServers.
func (mr *MockContextMockRecorder) VirtualServers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VirtualServers", reflect.TypeOf((*MockContext)(nil).VirtualServers))
}
