server:
  host: "127.0.0.1"
  externalUrl: "http://127.0.0.1:8081"
database:
  host: "localhost"
  port: 5732
  username: "user"
  password: "password"
  sslMode: "disable"
initialVirtualServer:
  enableRegistration: true
  initialAdmin:
    username: admin
    displayName: Admin
    primaryEmail: foo@bar.com
    passwordHash: "$argon2id$v=19$m=16,t=2,p=1$MTIzNDU2Nzg$QWu7e+sjG5knAdNLoKdLDg"
keyStore:
  mode: "directory"
  directory:
    path: "./keys"
mail:
  host: "localhost"
  port: 1025
  username: "foo"
  password: "bar"
redis:
  host: "localhost"
