server:
  host: "127.0.0.1"
  port: 8081
  externalUrl: "http://127.0.0.1:8081"
frontend:
  externalUrl: "http://localhost:5173"
database:
  host: "localhost"
  port: 5732
  username: "user"
  password: "password"
  sslMode: "disable"
initialVirtualServer:
  enableRegistration: true
  createInitialAdmin: true
  signingAlgorithm: "RS256"
  initialAdmin:
    username: admin
    displayName: Admin
    primaryEmail: foo@bar.com
    passwordHash: "$argon2id$v=19$m=16,t=2,p=1$MTIzNDU2Nzg$QWu7e+sjG5knAdNLoKdLDg"
  initialApplications:
    - name: "test-application"
      displayName: "Test Application"
      type: "public"
      redirectUris:
        - "http://localhost:1234/login-callback"
      postLogoutRedirectUris:
        - "http://localhost:1234/logout-callback"
keyStore:
  mode: "directory"
  directory:
    path: "./keys"
mail:
  host: "localhost"
  port: 1025
  username: "foo"
  password: "bar"
cache:
  mode: memory
