server:
  host: "127.0.0.1"
  externalUrl: "127.0.0.1:8081"
database:
  host: "localhost"
  port: 5732
  username: "user"
  password: "password"
  sslMode: "disable"
initialVirtualServer:
  enableRegistration: true
keyStore:
  mode: "directory"
  directory:
    path: "./keys"
mail:
  host: "localhost"
  port: 1025
  username: "foo"
  password": "bar"
