// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/services/outbox (interfaces: MessageBroker)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_messageBroker.go -package=mocks . MessageBroker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageBroker is a mock of MessageBroker interface.
type MockMessageBroker struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBrokerMockRecorder
	isgomock struct{}
}

// MockMessageBrokerMockRecorder is the mock recorder for MockMessageBroker.
type MockMessageBrokerMockRecorder struct {
	mock *MockMessageBroker
}

// NewMockMessageBroker creates a new mock instance.
func NewMockMessageBroker(ctrl *gomock.Controller) *MockMessageBroker {
	mock := &MockMessageBroker{ctrl: ctrl}
	mock.recorder = &MockMessageBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBroker) EXPECT() *MockMessageBrokerMockRecorder {
	return m.recorder
}

// Distribute mocks base method.
func (m *MockMessageBroker) Distribute(ctx context.Context, message *repositories.OutboxMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Distribute", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Distribute indicates an expected call of Distribute.
func (mr *MockMessageBrokerMockRecorder) Distribute(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distribute", reflect.TypeOf((*MockMessageBroker)(nil).Distribute), ctx, message)
}
