// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/The127/Keyline/internal/repositories (interfaces: ApplicationKeyRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repositories/mocks/application_key_repository.go -package=mocks github.com/The127/Keyline/internal/repositories ApplicationKeyRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repositories "github.com/The127/Keyline/internal/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationKeyRepository is a mock of ApplicationKeyRepository interface.
type MockApplicationKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockApplicationKeyRepositoryMockRecorder is the mock recorder for MockApplicationKeyRepository.
type MockApplicationKeyRepositoryMockRecorder struct {
	mock *MockApplicationKeyRepository
}

// NewMockApplicationKeyRepository creates a new mock instance.
func NewMockApplicationKeyRepository(ctrl *gomock.Controller) *MockApplicationKeyRepository {
	mock := &MockApplicationKeyRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationKeyRepository) EXPECT() *MockApplicationKeyRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockApplicationKeyRepository) Delete(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", id)
}

// Delete indicates an expected call of Delete.
func (mr *MockApplicationKeyRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApplicationKeyRepository)(nil).Delete), id)
}

// FirstOrErr mocks base method.
func (m *MockApplicationKeyRepository) FirstOrErr(ctx context.Context, filter *repositories.ApplicationKeyFilter) (*repositories.ApplicationKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrErr", ctx, filter)
	ret0, _ := ret[0].(*repositories.ApplicationKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrErr indicates an expected call of FirstOrErr.
func (mr *MockApplicationKeyRepositoryMockRecorder) FirstOrErr(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrErr", reflect.TypeOf((*MockApplicationKeyRepository)(nil).FirstOrErr), ctx, filter)
}

// FirstOrNil mocks base method.
func (m *MockApplicationKeyRepository) FirstOrNil(ctx context.Context, filter *repositories.ApplicationKeyFilter) (*repositories.ApplicationKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.ApplicationKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrNil indicates an expected call of FirstOrNil.
func (mr *MockApplicationKeyRepositoryMockRecorder) FirstOrNil(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockApplicationKeyRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockApplicationKeyRepository) Insert(applicationKey *repositories.ApplicationKey) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", applicationKey)
}

// Insert indicates an expected call of Insert.
func (mr *MockApplicationKeyRepositoryMockRecorder) Insert(applicationKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockApplicationKeyRepository)(nil).Insert), applicationKey)
}

// List mocks base method.
func (m *MockApplicationKeyRepository) List(ctx context.Context, filter *repositories.ApplicationKeyFilter) ([]*repositories.ApplicationKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.ApplicationKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApplicationKeyRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApplicationKeyRepository)(nil).List), ctx, filter)
}
