// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: ApplicationUserMetadataRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/application_user_metadata_repository.go -package=mocks Keyline/internal/repositories ApplicationUserMetadataRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApplicationUserMetadataRepository is a mock of ApplicationUserMetadataRepository interface.
type MockApplicationUserMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationUserMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockApplicationUserMetadataRepositoryMockRecorder is the mock recorder for MockApplicationUserMetadataRepository.
type MockApplicationUserMetadataRepositoryMockRecorder struct {
	mock *MockApplicationUserMetadataRepository
}

// NewMockApplicationUserMetadataRepository creates a new mock instance.
func NewMockApplicationUserMetadataRepository(ctrl *gomock.Controller) *MockApplicationUserMetadataRepository {
	mock := &MockApplicationUserMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationUserMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationUserMetadataRepository) EXPECT() *MockApplicationUserMetadataRepositoryMockRecorder {
	return m.recorder
}

// FirstOrNil mocks base method.
func (m *MockApplicationUserMetadataRepository) FirstOrNil(ctx context.Context, filter *repositories.ApplicationUserMetadataFilter) (*repositories.ApplicationUserMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.ApplicationUserMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockApplicationUserMetadataRepositoryMockRecorder) First(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockApplicationUserMetadataRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockApplicationUserMetadataRepository) Insert(applicationUserMetadata *repositories.ApplicationUserMetadata) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", applicationUserMetadata)
}

// Insert indicates an expected call of Insert.
func (mr *MockApplicationUserMetadataRepositoryMockRecorder) Insert(applicationUserMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockApplicationUserMetadataRepository)(nil).Insert), applicationUserMetadata)
}

// List mocks base method.
func (m *MockApplicationUserMetadataRepository) List(ctx context.Context, filter *repositories.ApplicationUserMetadataFilter) ([]*repositories.ApplicationUserMetadata, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.ApplicationUserMetadata)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockApplicationUserMetadataRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApplicationUserMetadataRepository)(nil).List), ctx, filter)
}

// Single mocks base method.
func (m *MockApplicationUserMetadataRepository) Single(ctx context.Context, filter *repositories.ApplicationUserMetadataFilter) (*repositories.ApplicationUserMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Single", ctx, filter)
	ret0, _ := ret[0].(*repositories.ApplicationUserMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Single indicates an expected call of Single.
func (mr *MockApplicationUserMetadataRepositoryMockRecorder) Single(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Single", reflect.TypeOf((*MockApplicationUserMetadataRepository)(nil).Single), ctx, filter)
}

// Update mocks base method.
func (m *MockApplicationUserMetadataRepository) Update(applicationUserMetadata *repositories.ApplicationUserMetadata) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", applicationUserMetadata)
}

// Update indicates an expected call of Update.
func (mr *MockApplicationUserMetadataRepositoryMockRecorder) Update(applicationUserMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApplicationUserMetadataRepository)(nil).Update), applicationUserMetadata)
}
