// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: GroupRoleRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/grouprole_repository.go -package=mocks Keyline/internal/repositories GroupRoleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockGroupRoleRepository is a mock of GroupRoleRepository interface.
type MockGroupRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupRoleRepositoryMockRecorder is the mock recorder for MockGroupRoleRepository.
type MockGroupRoleRepositoryMockRecorder struct {
	mock *MockGroupRoleRepository
}

// NewMockGroupRoleRepository creates a new mock instance.
func NewMockGroupRoleRepository(ctrl *gomock.Controller) *MockGroupRoleRepository {
	mock := &MockGroupRoleRepository{ctrl: ctrl}
	mock.recorder = &MockGroupRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRoleRepository) EXPECT() *MockGroupRoleRepositoryMockRecorder {
	return m.recorder
}
