// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/The127/Keyline/internal/repositories (interfaces: IdentityProviderRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/identity_provider_repository.go -package=mocks github.com/The127/Keyline/internal/repositories IdentityProviderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repositories "github.com/The127/Keyline/internal/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityProviderRepository is a mock of IdentityProviderRepository interface.
type MockIdentityProviderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityProviderRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityProviderRepositoryMockRecorder is the mock recorder for MockIdentityProviderRepository.
type MockIdentityProviderRepositoryMockRecorder struct {
	mock *MockIdentityProviderRepository
}

// NewMockIdentityProviderRepository creates a new mock instance.
func NewMockIdentityProviderRepository(ctrl *gomock.Controller) *MockIdentityProviderRepository {
	mock := &MockIdentityProviderRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityProviderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityProviderRepository) EXPECT() *MockIdentityProviderRepositoryMockRecorder {
	return m.recorder
}

// FirstOrErr mocks base method.
func (m *MockIdentityProviderRepository) FirstOrErr(ctx context.Context, filter *repositories.IdentityProviderFilter) (*repositories.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrErr", ctx, filter)
	ret0, _ := ret[0].(*repositories.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrErr indicates an expected call of FirstOrErr.
func (mr *MockIdentityProviderRepositoryMockRecorder) FirstOrErr(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrErr", reflect.TypeOf((*MockIdentityProviderRepository)(nil).FirstOrErr), ctx, filter)
}

// FirstOrNil mocks base method.
func (m *MockIdentityProviderRepository) FirstOrNil(ctx context.Context, filter *repositories.IdentityProviderFilter) (*repositories.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrNil indicates an expected call of FirstOrNil.
func (mr *MockIdentityProviderRepositoryMockRecorder) FirstOrNil(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockIdentityProviderRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockIdentityProviderRepository) Insert(identityProvider *repositories.IdentityProvider) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", identityProvider)
}

// Insert indicates an expected call of Insert.
func (mr *MockIdentityProviderRepositoryMockRecorder) Insert(identityProvider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIdentityProviderRepository)(nil).Insert), identityProvider)
}

// List mocks base method.
func (m *MockIdentityProviderRepository) List(ctx context.Context, filter *repositories.IdentityProviderFilter) ([]*repositories.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIdentityProviderRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIdentityProviderRepository)(nil).List), ctx, filter)
}
