// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: OutboxMessageRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/outboxmessage_repository.go -package=mocks Keyline/internal/repositories OutboxMessageRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxMessageRepository is a mock of OutboxMessageRepository interface.
type MockOutboxMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxMessageRepositoryMockRecorder is the mock recorder for MockOutboxMessageRepository.
type MockOutboxMessageRepositoryMockRecorder struct {
	mock *MockOutboxMessageRepository
}

// NewMockOutboxMessageRepository creates a new mock instance.
func NewMockOutboxMessageRepository(ctrl *gomock.Controller) *MockOutboxMessageRepository {
	mock := &MockOutboxMessageRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxMessageRepository) EXPECT() *MockOutboxMessageRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockOutboxMessageRepository) Delete(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", id)
}

// Delete indicates an expected call of Delete.
func (mr *MockOutboxMessageRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOutboxMessageRepository)(nil).Delete), id)
}

// Insert mocks base method.
func (m *MockOutboxMessageRepository) Insert(outboxMessage *repositories.OutboxMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", outboxMessage)
}

// Insert indicates an expected call of Insert.
func (mr *MockOutboxMessageRepositoryMockRecorder) Insert(outboxMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockOutboxMessageRepository)(nil).Insert), outboxMessage)
}

// List mocks base method.
func (m *MockOutboxMessageRepository) List(ctx context.Context, filter *repositories.OutboxMessageFilter) ([]*repositories.OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOutboxMessageRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOutboxMessageRepository)(nil).List), ctx, filter)
}
