// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: PasswordRuleRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/passwordrule_repository.go -package=mocks Keyline/internal/repositories PasswordRuleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordRuleRepository is a mock of PasswordRuleRepository interface.
type MockPasswordRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordRuleRepositoryMockRecorder is the mock recorder for MockPasswordRuleRepository.
type MockPasswordRuleRepositoryMockRecorder struct {
	mock *MockPasswordRuleRepository
}

// NewMockPasswordRuleRepository creates a new mock instance.
func NewMockPasswordRuleRepository(ctrl *gomock.Controller) *MockPasswordRuleRepository {
	mock := &MockPasswordRuleRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordRuleRepository) EXPECT() *MockPasswordRuleRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPasswordRuleRepository) Delete(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", id)
}

// Delete indicates an expected call of Delete.
func (mr *MockPasswordRuleRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasswordRuleRepository)(nil).Delete), id)
}

// FirstOrNil mocks base method.
func (m *MockPasswordRuleRepository) FirstOrNil(ctx context.Context, filter *repositories.PasswordRuleFilter) (*repositories.PasswordRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.PasswordRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockPasswordRuleRepositoryMockRecorder) First(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockPasswordRuleRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockPasswordRuleRepository) Insert(passwordRule *repositories.PasswordRule) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", passwordRule)
}

// Insert indicates an expected call of Insert.
func (mr *MockPasswordRuleRepositoryMockRecorder) Insert(passwordRule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockPasswordRuleRepository)(nil).Insert), passwordRule)
}

// List mocks base method.
func (m *MockPasswordRuleRepository) List(ctx context.Context, filter *repositories.PasswordRuleFilter) ([]*repositories.PasswordRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.PasswordRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPasswordRuleRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPasswordRuleRepository)(nil).List), ctx, filter)
}

// Single mocks base method.
func (m *MockPasswordRuleRepository) Single(ctx context.Context, filter *repositories.PasswordRuleFilter) (*repositories.PasswordRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Single", ctx, filter)
	ret0, _ := ret[0].(*repositories.PasswordRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Single indicates an expected call of Single.
func (mr *MockPasswordRuleRepositoryMockRecorder) Single(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Single", reflect.TypeOf((*MockPasswordRuleRepository)(nil).Single), ctx, filter)
}

// Update mocks base method.
func (m *MockPasswordRuleRepository) Update(passwordRule *repositories.PasswordRule) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", passwordRule)
}

// Update indicates an expected call of Update.
func (mr *MockPasswordRuleRepositoryMockRecorder) Update(passwordRule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPasswordRuleRepository)(nil).Update), passwordRule)
}
