// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: ResourceServerScopeRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/resource_server_scope_repository.go -package=mocks Keyline/internal/repositories ResourceServerScopeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceServerScopeRepository is a mock of ResourceServerScopeRepository interface.
type MockResourceServerScopeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResourceServerScopeRepositoryMockRecorder
	isgomock struct{}
}

// MockResourceServerScopeRepositoryMockRecorder is the mock recorder for MockResourceServerScopeRepository.
type MockResourceServerScopeRepositoryMockRecorder struct {
	mock *MockResourceServerScopeRepository
}

// NewMockResourceServerScopeRepository creates a new mock instance.
func NewMockResourceServerScopeRepository(ctrl *gomock.Controller) *MockResourceServerScopeRepository {
	mock := &MockResourceServerScopeRepository{ctrl: ctrl}
	mock.recorder = &MockResourceServerScopeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceServerScopeRepository) EXPECT() *MockResourceServerScopeRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockResourceServerScopeRepository) Delete(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", id)
}

// Delete indicates an expected call of Delete.
func (mr *MockResourceServerScopeRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResourceServerScopeRepository)(nil).Delete), id)
}

// FirstOrNil mocks base method.
func (m *MockResourceServerScopeRepository) FirstOrNil(ctx context.Context, filter *repositories.ResourceServerScopeFilter) (*repositories.ResourceServerScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.ResourceServerScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockResourceServerScopeRepositoryMockRecorder) First(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockResourceServerScopeRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockResourceServerScopeRepository) Insert(resourceServerScope *repositories.ResourceServerScope) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", resourceServerScope)
}

// Insert indicates an expected call of Insert.
func (mr *MockResourceServerScopeRepositoryMockRecorder) Insert(resourceServerScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockResourceServerScopeRepository)(nil).Insert), resourceServerScope)
}

// List mocks base method.
func (m *MockResourceServerScopeRepository) List(ctx context.Context, filter *repositories.ResourceServerScopeFilter) ([]*repositories.ResourceServerScope, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.ResourceServerScope)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockResourceServerScopeRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceServerScopeRepository)(nil).List), ctx, filter)
}

// FirstOrErr mocks base method.
func (m *MockResourceServerScopeRepository) FirstOrErr(ctx context.Context, filter *repositories.ResourceServerScopeFilter) (*repositories.ResourceServerScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrErr", ctx, filter)
	ret0, _ := ret[0].(*repositories.ResourceServerScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Single indicates an expected call of Single.
func (mr *MockResourceServerScopeRepositoryMockRecorder) Single(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrErr", reflect.TypeOf((*MockResourceServerScopeRepository)(nil).FirstOrErr), ctx, filter)
}

// Update mocks base method.
func (m *MockResourceServerScopeRepository) Update(resourceServerScope *repositories.ResourceServerScope) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", resourceServerScope)
}

// Update indicates an expected call of Update.
func (mr *MockResourceServerScopeRepositoryMockRecorder) Update(resourceServerScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourceServerScopeRepository)(nil).Update), resourceServerScope)
}
