// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: ResourceServerRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/resource_server_repository.go -package=mocks Keyline/internal/repositories ResourceServerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceServerRepository is a mock of ResourceServerRepository interface.
type MockResourceServerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResourceServerRepositoryMockRecorder
	isgomock struct{}
}

// MockResourceServerRepositoryMockRecorder is the mock recorder for MockResourceServerRepository.
type MockResourceServerRepositoryMockRecorder struct {
	mock *MockResourceServerRepository
}

// NewMockResourceServerRepository creates a new mock instance.
func NewMockResourceServerRepository(ctrl *gomock.Controller) *MockResourceServerRepository {
	mock := &MockResourceServerRepository{ctrl: ctrl}
	mock.recorder = &MockResourceServerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceServerRepository) EXPECT() *MockResourceServerRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockResourceServerRepository) Delete(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", id)
}

// Delete indicates an expected call of Delete.
func (mr *MockResourceServerRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResourceServerRepository)(nil).Delete), id)
}

// FirstOrNil mocks base method.
func (m *MockResourceServerRepository) FirstOrNil(ctx context.Context, filter *repositories.ResourceServerFilter) (*repositories.ResourceServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.ResourceServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockResourceServerRepositoryMockRecorder) First(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockResourceServerRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockResourceServerRepository) Insert(resourceServer *repositories.ResourceServer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", resourceServer)
}

// Insert indicates an expected call of Insert.
func (mr *MockResourceServerRepositoryMockRecorder) Insert(resourceServer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockResourceServerRepository)(nil).Insert), resourceServer)
}

// List mocks base method.
func (m *MockResourceServerRepository) List(ctx context.Context, filter *repositories.ResourceServerFilter) ([]*repositories.ResourceServer, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.ResourceServer)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockResourceServerRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceServerRepository)(nil).List), ctx, filter)
}

// Single mocks base method.
func (m *MockResourceServerRepository) Single(ctx context.Context, filter *repositories.ResourceServerFilter) (*repositories.ResourceServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Single", ctx, filter)
	ret0, _ := ret[0].(*repositories.ResourceServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Single indicates an expected call of Single.
func (mr *MockResourceServerRepositoryMockRecorder) Single(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Single", reflect.TypeOf((*MockResourceServerRepository)(nil).Single), ctx, filter)
}

// Update mocks base method.
func (m *MockResourceServerRepository) Update(resourceServer *repositories.ResourceServer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", resourceServer)
}

// Update indicates an expected call of Update.
func (mr *MockResourceServerRepositoryMockRecorder) Update(resourceServer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourceServerRepository)(nil).Update), resourceServer)
}
