// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: SessionRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/session_repository.go -package=mocks Keyline/internal/repositories SessionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", id)
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), id)
}

// FirstOrErr mocks base method.
func (m *MockSessionRepository) FirstOrErr(ctx context.Context, filter *repositories.SessionFilter) (*repositories.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrErr", ctx, filter)
	ret0, _ := ret[0].(*repositories.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrErr indicates an expected call of FirstOrErr.
func (mr *MockSessionRepositoryMockRecorder) FirstOrErr(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrErr", reflect.TypeOf((*MockSessionRepository)(nil).FirstOrErr), ctx, filter)
}

// FirstOrNil mocks base method.
func (m *MockSessionRepository) FirstOrNil(ctx context.Context, filter *repositories.SessionFilter) (*repositories.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrNil indicates an expected call of FirstOrNil.
func (mr *MockSessionRepositoryMockRecorder) FirstOrNil(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockSessionRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockSessionRepository) Insert(session *repositories.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", session)
}

// Insert indicates an expected call of Insert.
func (mr *MockSessionRepositoryMockRecorder) Insert(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSessionRepository)(nil).Insert), session)
}
