// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/user_repository.go -package=mocks Keyline/internal/repositories UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FirstOrErr mocks base method.
func (m *MockUserRepository) FirstOrErr(ctx context.Context, filter *repositories.UserFilter) (*repositories.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrErr", ctx, filter)
	ret0, _ := ret[0].(*repositories.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrErr indicates an expected call of FirstOrErr.
func (mr *MockUserRepositoryMockRecorder) FirstOrErr(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrErr", reflect.TypeOf((*MockUserRepository)(nil).FirstOrErr), ctx, filter)
}

// FirstOrNil mocks base method.
func (m *MockUserRepository) FirstOrNil(ctx context.Context, filter *repositories.UserFilter) (*repositories.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrNil indicates an expected call of FirstOrNil.
func (mr *MockUserRepositoryMockRecorder) FirstOrNil(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockUserRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockUserRepository) Insert(user *repositories.User) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", user)
}

// Insert indicates an expected call of Insert.
func (mr *MockUserRepositoryMockRecorder) Insert(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUserRepository)(nil).Insert), user)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, filter *repositories.UserFilter) ([]*repositories.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockUserRepository) Update(user *repositories.User) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", user)
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), user)
}
