// Code generated by MockGen. DO NOT EDIT.
// Source: Keyline/internal/repositories (interfaces: VirtualServerRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/virtualserver_repository.go -package=mocks Keyline/internal/repositories VirtualServerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repositories "Keyline/internal/repositories"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVirtualServerRepository is a mock of VirtualServerRepository interface.
type MockVirtualServerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualServerRepositoryMockRecorder
	isgomock struct{}
}

// MockVirtualServerRepositoryMockRecorder is the mock recorder for MockVirtualServerRepository.
type MockVirtualServerRepositoryMockRecorder struct {
	mock *MockVirtualServerRepository
}

// NewMockVirtualServerRepository creates a new mock instance.
func NewMockVirtualServerRepository(ctrl *gomock.Controller) *MockVirtualServerRepository {
	mock := &MockVirtualServerRepository{ctrl: ctrl}
	mock.recorder = &MockVirtualServerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualServerRepository) EXPECT() *MockVirtualServerRepositoryMockRecorder {
	return m.recorder
}

// FirstOrErr mocks base method.
func (m *MockVirtualServerRepository) FirstOrErr(ctx context.Context, filter *repositories.VirtualServerFilter) (*repositories.VirtualServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrErr", ctx, filter)
	ret0, _ := ret[0].(*repositories.VirtualServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrErr indicates an expected call of FirstOrErr.
func (mr *MockVirtualServerRepositoryMockRecorder) FirstOrErr(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrErr", reflect.TypeOf((*MockVirtualServerRepository)(nil).FirstOrErr), ctx, filter)
}

// FirstOrNil mocks base method.
func (m *MockVirtualServerRepository) FirstOrNil(ctx context.Context, filter *repositories.VirtualServerFilter) (*repositories.VirtualServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrNil", ctx, filter)
	ret0, _ := ret[0].(*repositories.VirtualServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrNil indicates an expected call of FirstOrNil.
func (mr *MockVirtualServerRepositoryMockRecorder) FirstOrNil(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrNil", reflect.TypeOf((*MockVirtualServerRepository)(nil).FirstOrNil), ctx, filter)
}

// Insert mocks base method.
func (m *MockVirtualServerRepository) Insert(virtualServer *repositories.VirtualServer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", virtualServer)
}

// Insert indicates an expected call of Insert.
func (mr *MockVirtualServerRepositoryMockRecorder) Insert(virtualServer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockVirtualServerRepository)(nil).Insert), virtualServer)
}

// List mocks base method.
func (m *MockVirtualServerRepository) List(ctx context.Context, filter *repositories.VirtualServerFilter) ([]*repositories.VirtualServer, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*repositories.VirtualServer)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVirtualServerRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVirtualServerRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockVirtualServerRepository) Update(virtualServer *repositories.VirtualServer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", virtualServer)
}

// Update indicates an expected call of Update.
func (mr *MockVirtualServerRepositoryMockRecorder) Update(virtualServer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVirtualServerRepository)(nil).Update), virtualServer)
}
