### create an application
POST http://127.0.0.1:8081/api/virtual-servers/keyline/applications
Content-Type: application/json

{
  "name": "foo",
  "displayName": "Foo Application",
  "redirectUris": [
    "http://localhost:1234",
    "http://localhost:3245"
  ]
}

### list all applicaitons
GET http://127.0.0.1:8081/api/virtual-servers/keyline/applications
Accept: application/json
