### create virtual server
POST http://127.0.0.1:8081/api/virtual-servers
Content-Type: application/json

{
  "name": "f",
  "displayName": "A",
  "enableRegistration": true
}

### get virtual server public info
GET http://127.0.0.1:8081/api/virtual-servers/keyline/public-info
