### get oidc config
GET http://127.0.0.1:8081/oidc/keyline/.well-known/openid-configuration

### get signing key for virtual server
GET http://127.0.0.1:8081/oidc/keyline/.well-known/jwks.json

### start auth flow
# @no-redirect
GET http://127.0.0.1:8081/oidc/keyline/authorize
    ?client_id=admin-ui
    &redirect_uri=http://localhost:3000
    &response_type=code
    &scope=oidc email profile

### execute code flow
POST http://127.0.0.1:8081/oidc/keyline/token
Content-Type: application/x-www-form-urlencoded

grant_type = authorization_code &
client_id = admin-ui &
redirect_uri = http://localhost:5173/debugRedirectTarget &
code = NRNvT8WR8vq7_DACEmVzhA==

### refresh token
POST http://127.0.0.1:8081/oidc/keyline/token
Content-Type: application/x-www-form-urlencoded

grant_type = refresh_token &
client_id = admin-ui &
refresh_token = JuTNZ5aFU7CN9uGP3j0aHw==

