### list roles
GET http://127.0.0.1:8081/api/virtual-servers/keyline/roles

### get a role
GET http://127.0.0.1:8081/api/virtual-servers/keyline/roles/a9f98fe3-85b4-4b91-8aae-a86969c20dbc

### create a role
POST http://127.0.0.1:8081/api/virtual-servers/keyline/roles
Content-Type: application/json

{
  "name": "role5",
  "description": "this is a demo role",
  "requiresMfa": true,
  "maxTokenAge": "12h"
}

### asign a role to a user
POST http://127.0.0.1:8081/api/virtual-servers/keyline/roles/967f2c56-b130-46c5-a46b-0a4c55d6c075/assign
Content-Type: application/json

{
  "userId": "4578cb87-7704-4c4d-b8b9-b7d67c8d43ce"
}

### list users in role
GET http://127.0.0.1:8081/api/virtual-servers/keyline/roles/967f2c56-b130-46c5-a46b-0a4c55d6c075/users
