### register a user
POST http://127.0.0.1:8081/api/virtual-servers/keyline/users/register
Content-Type: application/json

{
  "username": "foo469",
  "displayName": "Foo",
  "password": "foo",
  "email": "foo@bar.home"
}

### create a service user
POST http://127.0.0.1:8081/api/virtual-servers/keyline/users/create-service-user
Content-Type: application/json

{
  "username": "service-user-01"
}

### list users
GET http://127.0.0.1:8081/api/virtual-servers/keyline/users

