server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.41:8081/oidc/keyline
          audiences:
            - java-spring-example
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: TRACE
    com.nimbusds.jwt: TRACE
    com.nimbusds.jose: TRACE
