name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5732:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Run golangci-lint (v2)
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

      - name: Run unit tests
        run: go test -v ./...

      - name: Run integration tests
        run: go test -v ./tests/integration/... -tags=integration

      - name: Build binary
        run: go build ./...

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push dev image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          push: true
          tags: |
            ghcr.io/the127/keyline:latest
            ghcr.io/the127/keyline:dev-${{ github.run_number }}
            ghcr.io/the127/keyline:dev-${{ github.sha }}

  cleanup-old-dev-builds:
    runs-on: ubuntu-latest
    needs: lint-test-build
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: write
    steps:
      - name: Delete old dev build images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: keyline
          owner: The127
          keep-n-tagged: 10
          exclude-tags: latest,v*
          older-than: 7 days
