name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Run golangci-lint (v2)
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build ./...
